  version: '3.8'
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_USER: movie_web_user 
        POSTGRES_DB: movie_web_backend 
        POSTGRES_PASSWORD: YourPasswordHere 
      ports:
        - "5432:5432" 
      networks:
        - p-stream-network
    p-stream:
      image: ghcr.io/p-stream/backend:latest
      environment:
        MWB_POSTGRES__CONNECTION: postgresql://movie_web_user:YourPasswordHere@postgres:5432/movie_web_backend
        MWB_CRYPTO__SESSION_SECRET: 32CharacterLongStringHere 
        MWB_META__NAME: unofficial-backend
        MWB_POSTGRES__MIGRATE_ON_BOOT: "true"
        MIKRO_ORM_MIGRATIONS_DISABLE_FOREIGN_KEYS: "true" 
      ports:
        - "80:80"
      depends_on:
        - postgres
      networks:
        - p-stream-network
  networks:
    p-stream-network: 
      driver: bridge
